### ISSUE TITLE
Move to official repo?

### ISSUE THREAD

**Issue by kelset** [filipemerker/flatlist-performance-tips#2]
👋 @filipemerker !

The performance tips you wrote are indeed (IMHO) fairly useful and I think it would be great to see them in the documentation - it would be great if you could open a PR to https://github.com/facebook/react-native-website and integrate what you wrote in the main docs.

If you need help with that I'd love to lend a hand into doing this.

**Comment by filipemerker** [comment]
Hi @kelset! I would definitely appreciate some help on moving this to the docs! Sorry for the delay!

**Comment by kelset** [comment]
No problem!
Are you on twitter? Would you mind [sending me a DM there](https://twitter.com/Kelset) so that we can synch up later on this week on how to approach the PR? :)

**Comment by edreyyo** [comment]
Any news on this yet? The info contained here is a great asset to the RN community. It would be awesome to have some of it in the official docs.

**Comment by kelset** [comment]
uhm I think that we sort of both forgot about this 🙇‍♂️ I'll ping him and we'll see what do to :)

**Comment by edreyyo** [comment]
@kelset Excellent. I'm happy to help any way I can (proof-reading, formatting etc etc)

**Comment by ghost** [comment]
Hi , please help me my flatlist still works very slow even with 100 item without any photo.
Also when I scroll it new list are disappear for a few seconds.
How can I make it something like whatsapp or telegram messages or contact lists, to work fast and smooth scrolling.
Also i bring the list from asyncstorage but even works slow.

**Comment by SjoenH** [comment]
@muhammadwfa This is not a help section.Try the suggestions and if you still have problem you should ask somewhere like stack-overflow/chat/help-community.

**Comment by kelset** [comment]
(quick update: over twitter DMs I tried to ping Felipe but he never replied - atm there is a new effort to rewrite the website so maybe we can squeeze this in)

**Comment by filipemerker** [comment]
Sorry for the delay guys, but with the amazing help of @MohamadKh75 and @kelset (as referenced above) we are moving this article to the official docs. This way, I'll not update here anymore. Any update on this topic, I'll open as a PR to the docs.
